# Generated by Django 5.1.6 on 2025-02-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='categoryType',
        ),
    ]
